### ISSUE TITLE
no puedo hacer nada en javascreepy. 

### ISSUE THREAD

**Issue by gisela284** [bastiansg/burbusuenios#1]
Traté sacar el efecto de click y cambia el color de este ejemplo: https://threejs.org/examples/?q=inter#canvas_interactive_cubes y veo todo negro.

Me llevé las variables nuevas, y las funciones que creí que servían para eso. También reemplazé algún nombre de variable por el que usamos nosotrxs. Pero el error que me tira es extraño, como si faltara un archivo. y no hay ninguna parte donde haya incluido un archivo. entonces de donde sale ese archivo y como cambio la ruta?

no entiendo ¿qué hago mal? (además de todo)

HELP ME!  
https://www.youtube.com/watch?v=cueulBxn1Fw

**Comment by bastiansg** [comment]
Esto me pasó muchas veces, seguramente dentro de las funciones que importaste hay alguna variable que requiere de otro archivo js o alguna imagen o conjunto de imágenes, compara los index.html, fijate en las primeras lineas del index.html cuando importa archivos js externos para usar las funciones que se encuentran dentro de estos, por ejemplo en lo el index.html del burbusuenios hay una parte del tipo:
        
        <script src="js/three.js"></script>
	<script src="js/TypedArrayUtils.js"></script>
	<script src="js/controls/FirstPersonControls.js"></script>
	<script type="x-shader/x-vertex" id="vertexshader">

Ahí ves por ejemplo que estoy importando el archivo "TypedArrayUtils.js" que se encuantra en el path "js" el cual es un path relativo respecto a donde esta el index.html, el path absoluto sería:
"burbusuenios/public/js/TypedArrayUtils.js"

Y no digas que no podes, la clave del éxito es tener una alta tolerancia a los fracasos de los primeros pasos, así que tomatelo con calma.

take it easy babe
https://www.youtube.com/watch?v=n32cJLmHCsU
